name: "Integrate"

on:
    push:
        branches:
        - "master"
    pull_request: null

jobs:
    tests:
        name: "Tests"
        strategy:
            matrix:
                php-version:
                - "7.4"
                - "8.0"
        runs-on: "ubuntu-24.04"
        steps:
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@v2"
            with:
                php-version: "${{ matrix.php-version }}"
                coverage: "none"
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4"
        -
            name: "Install dependencies"
            run: "composer update --no-interaction"
        -
            name: "Execute tests"
            run: "composer run test --no-interaction"
